name: TestRoad

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-18.04
    env:
      SHA: "${GITHUB_SHA::8}"
    steps:
      - run: |
          echo $SHA
          "docker build -t 815882715903.dkr.ecr.ap-southeast-1.amazonaws.com/morchana-static-qr-code-api:$SHA8 ."
